### ISSUE TITLE
Would DeepMEI work with whole exome data?

### ISSUE THREAD

**Issue by RSWilson1** [xuxif/DeepMEI#1]
Hi, 

I was wondering if DeepMEI is compatible with whole exome data? If not, is this something that might be added in the future?

Best wishes,
Robert

**Comment by xuxif** [comment]
Hello,

DeepMEI is primarily intended for MEI identification in WGS data. We have attempted to use it on WES data in the past, but the results were rather complex. We applied it to a cohort of 12,000 individuals who were sequenced using targeted region sequencing (covering approximately 900 genes) to identify disease-causing MEIs. The challenge we faced was that true MEIs were mixed with false positive loci. We believe this might be due to a significant reduction in the count of true MEIs compared to the false positive loci. Ultimately, we had to visually inspect the data using IGV and validate the results with Sanger sequencing. Thankfully, the overall count was fairly low. This situation is quite different when applied to WGS data, where the count of true MEIs typically far exceeds that of false positive loci.

Best wishes,
Xiaofei
