### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by mwalker174** [xuxif/DeepMEI#3]
Hello,

We have been benchmarking DeepMEI for use in [gatk-sv](https://github.com/broadinstitute/gatk-sv). We try to maintain copies of Dockerfiles of all tools for reproducibility and security reasons. Would it be possible to make the Dockerfile available? Thanks!

**Comment by xuxif** [comment]
Absolutely, that's a great suggestion! However, I recommend waiting a few months. We're currently working on an updated version that will extend support to all types of structural variations (SV). This update is particularly exciting because it aims to bring the performance in short-read sequencing data on par with what we've achieved in long-read sequencing data. If you still need the Dockerfile, please feel free to leave your email address. We'll be happy to send it directly to you. Your interest in our project is greatly appreciated!

Additionally, it's worth noting that the corresponding article is still under review. As of now, we haven't received any feedback from the reviewers. In light of this, withdrawing the manuscript could be considered as an option. We'll keep you updated on any developments. Thanks for your interest and patience!

**Comment by mwalker174** [comment]
Thank you for your quick reply. Great to hear there are further improvements coming. In some preliminary benchmarking, DeepMEI is outperforming both MELT and Scramble already, although we need to do a deeper analysis.

Can you please send the Dockerfile to me at markw at broadinstitute dot org?

**Comment by xuxif** [comment]
Hello,

I wanted to update you regarding your request for the Dockerfile for DeepMEI. I've sent the Dockerfile along with detailed tips and additional information to your email. Please check your inbox for my message.

Given that we've addressed your request, I will be closing this topic on GitHub. However, should you have any further questions or require additional assistance, please don't hesitate to reach out to me via email. Alternatively, you are always welcome to open a new conversation here on GitHub.
